import { Button, LineEdit } from "std-widgets.slint";
export component AppWindow inherits Window {
  title: "Fibonacci Calculator";
  width: 800px;
  height: 450px;
  default-font-size : 16px;

  in-out property <string> result-success;
  in-out property <string> result-error;

  callback calculate-fibonacci(string);

  GridLayout {
    width: 450px;
    height: root.result-success != "" ? 225px + 48px : 225px;
    padding-top: 8px;
    padding-bottom: 8px;
    padding-left: 12px;
    padding-right: 12px;
    spacing: 8px;

    Row {
      Text {
        text: "Fibonacci Calculator";
        horizontal-alignment: center;
        font-size: 24px;
        color: green;
      }
    }

    Row {
      VerticalLayout {
        Text {
          height: 18px;
          text: "Insert an integer n to get the nth Fibonacci number:";
        }

        inputField := LineEdit {
          placeholder-text: "(Type integer here)";
          edited => {
            root.result-success = "";
            root.result-error = "";
          }
          accepted => {
            root.calculate-fibonacci(self.text);
            self.clear-focus();
          }
        }

        if root.result-error != "" : errorText := Text {
          height: 18px;
          text: root.result-error;
          color: red;
        }
      }
    }

    Row {
      Button {
        primary: true;
        text: "CALCULATE";
        clicked => {
          root.calculate-fibonacci(inputField.text);
          inputField.clear-focus();
        }
      }
    }

    Rectangle {
      visible: root.result-success != "" ? true : false;
      height: root.result-success != "" ? 48px : 0px;

      if root.result-success != "" : resultDisplay := Text {
        text: root.result-success;
        color: blue;
      }
    }
  }

}
